
type Events {
 event_id: String
 user_id: String
 user: UserInfo
 event_name: String
 event_date: String
 description: String
 meetup_location: String
 destination: String
 max_joiners: Int

}

type UserInfo {  
 user_info_id: ID
 given_name: String
 family_name: String
 phone_number: String
 address: String
 city: String
 province: String
 zip_code: String
 email: String! @unique(index: "uniqueEmail")
}


type Query {
 allEvents: [Events]
 eventById(event_id: String): [Events]
 eventByUser(user_id: String): [Events]
 userInfoByEmail(email: String): UserInfo
}
