
type Events {
 event_id: String
 user_id: String
 user: UserInfo
 event_name: String
 event_date: String
 description: String
 meetup_location: String
 destination: String
 max_joiners: Int
 joiners: [Joiners]! @relation
}


type UserInfo {  
 user_info_id: ID
 given_name: String
 family_name: String
 phone_number: String
 address: String
 city: String
 province: String
 zip_code: String
 email: String! @unique(index: "uniqueEmail")
}

type Joiners {
   user: UserInfo
   event: Events
   date_joined: String
   status: String
}


type Query {
 allEvents: [Events]
 eventById(_id: String): [Events]
 eventByUser(user_id: String): [Events]
 userInfoByEmail(email: String): UserInfo
}
