const Constants = {
    REQUEST_EVENTS: "REQUEST_EVENTS",
    REQUEST_EVENT_BY_USER: "REQUEST_EVENT_BY_USER",
    REQUEST_CREATE_UPDATE_EVENT: "REQUEST_CREATE_UPDATE_EVENT",
    REQUEST_CREATE_UPDATE_EVENT_SUCCESS:'REQUEST_CREATE_UPDATE_EVENT_SUCCESS',
    REQUEST_CREATE_UPDATE_EVENT_FAILED:'REQUEST_CREATE_UPDATE_EVENT_FAILED',
    SET_EVENTS_LIST: "SET_EVENTS_LIST",
    SET_EVENTS_LIST_BY_USER: "SET_EVENTS_LIST_BY_USER"
};

export default Constants;