const Constants = {
    REQUEST_EVENTS: "REQUEST_EVENTS",
    REQUEST_CREATE_UPDATE_EVENT: "REQUEST_CREATE_UPDATE_EVENT",
    REQUEST_CREATE_UPDATE_EVENT_SUCCESS:'REQUEST_CREATE_UPDATE_EVENT_SUCCESS',
    REQUEST_CREATE_UPDATE_EVENT_FAILED:'REQUEST_CREATE_UPDATE_EVENT_FAILED',
    SET_EVENTS_LIST: "SET_EVENTS_LIST"
};

export default Constants;