const Constants = {
    REQUEST_EVENTS: "REQUEST_EVENTS",
    REQUEST_EVENT_ID: "REQUEST_EVENT_ID",
    REQUEST_EVENT_BY_USER: "REQUEST_EVENT_BY_USER",
    REQUEST_CREATE_UPDATE_EVENT: "REQUEST_CREATE_UPDATE_EVENT",
    REQUEST_CREATE_UPDATE_EVENT_SUCCESS:'REQUEST_CREATE_UPDATE_EVENT_SUCCESS',
    REQUEST_CREATE_UPDATE_EVENT_FAILED:'REQUEST_CREATE_UPDATE_EVENT_FAILED',
    REQUEST_JOIN_EVENT:'REQUEST_JOIN_EVENT',
    SET_EVENTS_LIST: 'SET_EVENTS_LIST',
    SET_EVENTS_LIST_BY_USER: 'SET_EVENTS_LIST_BY_USER',
    REQUEST_JOIN_SUCCESS: 'REQUEST_JOIN_SUCCESS',
    
};

export default Constants;