const Constants = {
    REQUEST_SIGN_IN: "REQUEST_SIGN_IN",
    REQUEST_SIGN_UP: "REQUEST_SIGN_UP",
    REQUEST_CURRENT_USER: "REQUEST_CURRENT_USER",
    SET_CURRENT_USER: "SET_CURRENT_USER",
    REQUEST_USER_FAILED: "REQUEST_USER_FAILED",
};

export default Constants;